[package]
name = "socks-rev"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version="1.4.*", features=["sync", "net", "rt", "rt-multi-thread", "time", "io-util", "time"]}
anyhow = "1.0.*"
byteorder = "1.5"

clap = {version="4.4.12", features=["derive"]}
log = "0.4"
env_logger = "0.11"